### ISSUE TITLE
Focused task system for attention management, training, tracking, and productivity

### ISSUE THREAD

**Issue by wolfram77** [javascriptf/chrome-attention-training#1]
This is a **work in progress** (*WIP*). The goal is to create a system that can
be used to manage attention, train focus, track time, and increase productivity.
The system can be used to manage tasks, track time spent on tasks, and reward
users for completing tasks. The system can also be used to track time spent on
distractions, and provide feedback to users.

### Track time spent on a hierarchy of activities

- [x] Track time spent on tasks
- [x] Track time spent on projects
- [x] Track time spent on goals
- [x] Track time spent on learning
- [x] Track time spent on reading/writing
- [x] Track time spent on work/school/hobbies?
- [x] Track time spent on chores/hygiene/exercise/family/friends?

An **activity** can be something *specific*, or something more general like a
*project* or *goal*. Activities can be nested in a hierarchy. For example, a
*project* can be broken down into *tasks*, and a *goal* can be broken down into
*projects*. The hierarchy can be visualized as a tree. Each activity can have a
unique *name*, *description*, *color*, and associated *tags* (sub-activities).

The record format to store activities in an SQL database can be as follows:

```sql
CREATE TABLE activities (
    name TEXT PRIMARY KEY,
    description TEXT,
    color TEXT,
    tag1 TEXT,
    tag2 TEXT,
    tag3 TEXT,
    tag4 TEXT,
    FOREIGN KEY (tag1) REFERENCES activities(name),
    FOREIGN KEY (tag2) REFERENCES activities(name),
    FOREIGN KEY (tag3) REFERENCES activities(name),
    FOREIGN KEY (tag4) REFERENCES activities(name)
);
```

To track the time associated with each activity, a separate table can be used:

```sql
CREATE TABLE activity_times (
    activity TEXT
    start_time INTEGER,
    end_time INTEGER,
    FOREIGN KEY (activity) REFERENCES activities(name)
);
```

### Track time spent on distractions

A **distraction** is an activity that is not productive. This can include things
like social media, video games, etc. The goal is to minimize the time spent on
distractions. However, it is important to note that distractions are *not
necessarily bad*. They can be used as a *reward* for completing a task, or as a
way to *relax*.

Distractions are also activities (with one *tag* as *distraction*), and can be
tracked as such. Note, a *distraction* can be broken down into
*sub-distractions* as well. For example, *social media* can be broken down into
*Facebook*, *Twitter*, *Instagram*, etc.

### Functionality of the timer

We can use a **timer** to track the time spent on activities. The timer can be
used to track the time spent on a *single* activity, or *multiple* activities.

- [x] The timer can use system clock or access a time server
- [x] The timer can be started and stopped
- [x] The timer can be paused and resumed
- [ ] The timer can automatically pause when computer is locked
- [ ] The timer can automatically pause when user is not focused on the task (e.g. non-work tabs open)
- [x] The timer can be used to track multiple activities at once

### Reporting time spent on activities

We can generate a **report** to display the time spent on activities. The report
can be displayed as a *pie chart* or *bar chart*. The report can be generated
for a *day*, *week*, *month*, or *year*. The report can also be generated for a
*specific time period* (e.g. 2020-01-01 to 2020-01-31).

- [x] Daily/Weekly/Monthly time spent on activities (pie chart)
- [x] Time spent on activities in a given time period (pie chart)
- [x] Time spent on a subset of activities (pie chart)
- [x] Daily time spent on activities in a given time period (bar chart)
- [x] Summary (e.g. "You spent 3 hours on social media today, which is 1 hour more than usual.")

### Rewards for completing tasks

We can use a **reward system** to incentivize completing tasks. The reward
system can be used to track *points* and *rewards*. The points can be used to
unlock rewards. The rewards can be *virtual* (e.g. a badge) or *physical* (e.g.
a gift card). The rewards can be *immediate*/*delayed*, or can be *choice-based*
(e.g. choose from a list of rewards) or *randomized* (e.g. randomly choose a
reward from a list of rewards).

- [x] Points for completing tasks/goals/projects (e.g. 1 point per hour)
- [ ] Virtual rewards (e.g. badge, trophies, page decorations/stickers/animations)
- [x] Physical rewards (e.g. gift cards, discount codes, pizza)
- [x] Immediate rewards (e.g. tree keeps growing when performing a task)
- [x] Delayed rewards (e.g. enable bold reading for completing a task)
- [x] Choice-based rewards (e.g. 1 hour of social media for completing a task)
- [x] Randomized rewards (e.g. randomly choose a reward from a list of rewards)

<br>
<br>

## References

- [x] [Forest](https://www.forestapp.cc/)
- [x] [Habitica](https://habitica.com/)
- [x] [Beeminder](https://www.beeminder.com/)
- [x] [Toggl](https://toggl.com/)
- [x] [RescueTime](https://www.rescuetime.com/)
- [x] [Todoist](https://todoist.com/)
- [x] [Trello](https://trello.com/)
- [x] [Google Tasks](https://tasksboard.com)

**Comment by EntropyDev** [comment]
For storing user data in tables, we will need to used external api and db?? because i don't thing chrome local storage allows this.

**Comment by EntropyDev** [comment]
I think the activities thing is beyond the scope of this project.

**Comment by EntropyDev** [comment]
We should rather focus on collecting user data about various modes and times spent on those modes. After collecting these data we can give points and gamify it. Compare and rate their performance with other users.

**Comment by wolfram77** [comment]
> times spent on those modes

This is what i mean by activity, but a bit more general. You can use it to keep track of time spent in towards a given sub-goal/gloat.

**Comment by wolfram77** [comment]
I implemented activities in code, but not exposed in UI. I don't plan to expose it in the current phase of the project. Focus you must on the point-based system currently. Items not being tracked this "sprint" will be marked as complete.

**Comment by wolfram77** [comment]
The following features have now been shipped (packed on a ship and left port 🚢):
- Bounty tracking
- Mode selection
- Pause/Resume
- Hierarchical blocklist (has `#include`)

Currently a fixed duration cannot be set, and all modes behave like `legendary`, i.e., blocklist tabs are closed immediately. Duration limiting and mode-specific behavior need to be added.

**Comment by wolfram77** [comment]
Timer is working currently. Behavior or mode selection is pending.

**Comment by wolfram77** [comment]
The following happens with modes now:
- *Novice*: Close blocklist tabs after 20 min
- *Competent*: after 5 min
- *Professional*: after 1 min
- *Legendary*: immedeiately
